version: '3'

services:
  kharayoscraper:
    build: 
      context: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      -  FIREBASE_API_KEY=${FIREBASE_API_KEY}
      -  AUTH_DOMAIN=${AUTH_DOMAIN}
      -  DATABASE_URL=${DATABASE_URL}
      -  STORAGE_BUCKET=${STORAGE_BUCKET}
      -  GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      -  TZ=${TZ}

